openapi: 3.0.4
info:
  title: Username Profanity
  description: >-
    Username Profanity Checker is a simple tool for checking if a username is
    inappropriate or profane. It returns if the username is inappropriate or
    profane.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.0
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
  - url: https://api.apiverve.com/
paths:
  /v1/usernameprofanity:
    get:
      summary: Check Username
      description: Check if a username is inappropriate or profane
      operationId: usernameprofanity
      parameters:
        - name: username
          in: query
          schema:
            type: string
          required: true
          description: The username to check if it is inappropriate or profane
          example: b00bs
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: object
                    description: data
              example:
                status: ok
                error: null
                data:
                  username: b00bs
                  isProfane: true
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occurred, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
  - api_key: []
